### ISSUE TITLE
Gregoriotex falis when there is a space in filename.

### ISSUE THREAD

**Issue by warej** [gregorio-project/gregorio#1224]
_At first sorry if I'll write something stupid - I'm not much experienced with TeX and I'm absolutely new to Gregorio._

But from what I've observed, there is a bug with not quoting file names, which leads to compilation errors, when gabc file, tex file, or some directory on path to them contains a space in it's name ("ResHodie Nobis.gabc").

At first I've found the bug (missing quotes) at this [line](https://github.com/gregorio-project/gregorio/blob/master/tex/gregoriotex.lua#L555). Fixing them locally was not enough - caused another error, so I decided to leave it to someone, who's more into the project.
#### Environment info

OS: Windows 7 x64
Gregoriotex version (comment from gregoriotex.tex file):
`%      [2016/07/05 v4.2.0-rc2 GregorioTeX system.]% PARSE_VERSION_DATE_LTX`
#### Compilation log

```
This is LuaTeX, Version 0.95.0 (TeX Live 2016/W32TeX) 
 system commands enabled.
("./Res_Hodie nobis.tex"
LaTeX2e <2016/03/31> patch level 2
Babel <3.9r> and hyphenation patterns for 1 language(s) loaded.
(c:/texlive/2016/texmf-dist/tex/latex/base/article.cls
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
(c:/texlive/2016/texmf-dist/tex/latex/base/size10.clo))
(c:/texlive/2016/texmf-dist/tex/latex/fontspec/fontspec.sty
(c:/texlive/2016/texmf-dist/tex/latex/l3kernel/expl3.sty
(c:/texlive/2016/texmf-dist/tex/latex/l3kernel/expl3-code.tex)
(c:/texlive/2016/texmf-dist/tex/latex/l3kernel/l3pdfmode.def))
(c:/texlive/2016/texmf-dist/tex/latex/l3packages/xparse/xparse.sty)
(c:/texlive/2016/texmf-dist/tex/luatex/luaotfload/luaotfload.sty(using write ca
che: C:/texlive/2016/texmf-var/luatex-cache/generic)(using read cache: C:/texli
ve/2016/texmf-var/luatex-cache/generic C:/Users/virt/.texlive2016/texmf-var/lua
tex-cache/generic)
luaotfload | main : initialization completed in 0.344 seconds)
(c:/texlive/2016/texmf-dist/tex/latex/fontspec/fontspec-luatex.sty
(c:/texlive/2016/texmf-dist/tex/latex/base/fontenc.sty
(c:/texlive/2016/texmf-dist/tex/latex/euenc/eu2enc.def)
(c:/texlive/2016/texmf-dist/tex/latex/euenc/eu2lmr.fd)(load luc: C:/texlive/201
6/texmf-var/luatex-cache/generic/fonts/otl/lmroman10-regular.luc))
(c:/texlive/2016/texmf-dist/tex/xelatex/xunicode/xunicode.sty
(c:/texlive/2016/texmf-dist/tex/latex/tipa/t3enc.def(load luc: C:/texlive/2016/
texmf-var/luatex-cache/generic/fonts/otl/lmromanslant10-regular.luc)(load luc: 
C:/texlive/2016/texmf-var/luatex-cache/generic/fonts/otl/lmroman10-italic.luc)(
load luc: C:/texlive/2016/texmf-var/luatex-cache/generic/fonts/otl/lmroman10-bo
ld.luc) (c:/texlive/2016/texmf-dist/tex/latex/euenc/eu2lmss.fd)(load luc: C:/te
xlive/2016/texmf-var/luatex-cache/generic/fonts/otl/lmsans10-regular.luc))
(c:/texlive/2016/texmf-dist/tex/latex/graphics/graphicx.sty
(c:/texlive/2016/texmf-dist/tex/latex/graphics/keyval.sty)
(c:/texlive/2016/texmf-dist/tex/latex/graphics/graphics.sty
(c:/texlive/2016/texmf-dist/tex/latex/graphics/trig.sty)
(c:/texlive/2016/texmf-dist/tex/latex/graphics-cfg/graphics.cfg)
(c:/texlive/2016/texmf-dist/tex/latex/graphics-def/luatex.def
(c:/texlive/2016/texmf-dist/tex/generic/oberdiek/infwarerr.sty)
(c:/texlive/2016/texmf-dist/tex/generic/oberdiek/ltxcmds.sty)))))
(c:/texlive/2016/texmf-dist/tex/latex/fontspec/fontspec.cfg)))
(c:/texlive/texmf-local/tex/lualatex/gregoriotex/gregoriotex.sty
(c:/texlive/2016/texmf-dist/tex/latex/xcolor/xcolor.sty
(c:/texlive/2016/texmf-dist/tex/latex/graphics-cfg/color.cfg))
(c:/texlive/2016/texmf-dist/tex/latex/oberdiek/kvoptions.sty
(c:/texlive/2016/texmf-dist/tex/generic/oberdiek/kvsetkeys.sty
(c:/texlive/2016/texmf-dist/tex/generic/oberdiek/etexcmds.sty
(c:/texlive/2016/texmf-dist/tex/generic/oberdiek/ifluatex.sty))))
(c:/texlive/2016/texmf-dist/tex/luatex/luatexbase/luatexbase.sty
(c:/texlive/2016/texmf-dist/tex/luatex/ctablestack/ctablestack.sty))
(c:/texlive/2016/texmf-dist/tex/luatex/luamplib/luamplib.sty)
(c:/texlive/2016/texmf-dist/tex/generic/xstring/xstring.sty
(c:/texlive/2016/texmf-dist/tex/generic/xstring/xstring.tex))
(c:/texlive/texmf-local/tex/luatex/gregoriotex/gregoriotex-main.tex
("Res_Hodie nobis".gaux)
(c:/texlive/texmf-local/tex/luatex/gregoriotex/gregoriotex-spaces.tex)(load luc
: C:/texlive/2016/texmf-var/luatex-cache/generic/fonts/otl/greciliae.luc)
(c:/texlive/texmf-local/tex/luatex/gregoriotex/gregoriotex-chars.tex)
(c:/texlive/texmf-local/tex/luatex/gregoriotex/gregoriotex-signs.tex)
(c:/texlive/texmf-local/tex/luatex/gregoriotex/gregoriotex-syllable.tex)
(c:/texlive/texmf-local/tex/luatex/gregoriotex/gregoriotex-symbols.tex(load luc
: C:/texlive/2016/texmf-var/luatex-cache/generic/fonts/otl/greextra.luc))
(c:/texlive/texmf-local/tex/luatex/gregoriotex/gsp-default.tex)
(c:/texlive/texmf-local/tex/luatex/gregoriotex/gregoriotex-nabc.tex)))

LaTeX Warning: Unused global option(s):
    [14pt].

No file "Res_Hodie nobis".aux.
(c:/texlive/2016/texmf-dist/tex/latex/tipa/t3cmr.fd)
(c:/texlive/2016/texmf-dist/tex/context/base/mkii/supp-pdf.mkii
[Loading MPS to PDF converter (version 2006.09.02).]
) (c:/texlive/2016/texmf-dist/tex/latex/oberdiek/epstopdf-base.sty
(c:/texlive/2016/texmf-dist/tex/latex/oberdiek/grfext.sty
(c:/texlive/2016/texmf-dist/tex/generic/oberdiek/kvdefinekeys.sty))
(c:/texlive/2016/texmf-dist/tex/generic/oberdiek/pdftexcmds.sty
(c:/texlive/2016/texmf-dist/tex/generic/oberdiek/ifpdf.sty)
(c:/texlive/2016/texmf-dist/tex/generic/oberdiek/luatex-loader.sty
(c:/texlive/2016/texmf-dist/scripts/oberdiek/oberdiek.luatex.lua)))
(c:/texlive/2016/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg))ignored arguments: nobis-4_2_0-rc2.glog Res_Hodie nobis.gabc
Usage: gregorio [OPTION]... [-s | INPUT_FILE]
Try 'gregorio --help' for more information.
Proceeding anyway...
error: can't open file nobis-4_2_0-rc2.gtex for reading
c:/texlive/
2016/texmf-dist/tex/latex/base/ltluatex.lua:109: 
Module gregoriotex Error: 
(gregoriotex)             An error occured when compiling the score file
(gregoriotex)             'Res_Hodie nobis.gabc' with gregorio.
(gregoriotex)             Please check your score file. on input line 10

stack traceback:
    [C]: in function 'error'
    c:/texlive/2016/texmf-dist/tex/latex/base/ltluatex.lua:109: in function <c:/te
xlive/2016/texmf-dist/tex/latex/base/ltluatex.lua:108>
    (...tail calls...)
    ...xlive/texmf-local/tex/luatex/gregoriotex/gregoriotex.lua:737: in function '
compile_gabc'
    ...xlive/texmf-local/tex/luatex/gregoriotex/gregoriotex.lua:791: in function '
include_score'
    [\directlua]:1: in main chunk.
\gre@gregorioscore ...allowdeprecated@asboolean )}
                                                  \or \gre@debugmsg {compile...

l.10 \gregorioscore{Res_Hodie nobis}

? 
```

**Comment by eroux** [comment]
Interesting, thanks a lot for the report! Here the culprit is more LuaTeX than Gregorio, but the line you indicated clearly could be improved, and we could also replace all filename-unfriendly characters (_, @, space, etc.) with hyphens...

**Comment by eschwab** [comment]
I thought that we allow `_` in filenames since we tack on the version number as `4_2_0-rc3`? In any case I have the following list of characters in filenames to swap out with hyphens:

`space + & % * ?  $ @ : ; & ! #`

Am I missing any?

**Comment by eroux** [comment]
oh,  you're right about `_`. I think your list is enough, it should be quite easy to add a character if we missed one anyway

**Comment by henryso** [comment]
How about `"`, `'`, and `?

**Comment by warej** [comment]
Well, but if I get it right, the file names are created on the basis of existing .tex or .gabc files, so if previous file exists in the filesystem => it must contain only valid characters.
That's why I'd suggest to only escape spaces|quote whole name to support names with spaces.
_Just 0.02€ from my side._

**Comment by eroux** [comment]
well, why not all these characters also, although I doubt it will be helpful... but who knows...

**Comment by warej** [comment]
imo quoting each parameter (e.g. `$> command -file "some/test/file with spaces and $%"`) prevents shell from interpreting them.
And having the same name for tex file, gabc file and all other, created automatically is convenient. When you'd replace some signs with `-` or `_`, the name will be different (not much, but different). I'm not sure if it won't break some features (e.g. automatic temporary files cleanup).

**Comment by henryso** [comment]
The problem is with TeX.  TeX interprets certain characters in a weird way, doing things like collapsing multiple spaces into one, and there's no perfect way to "quote" the filename, which is why @eroux said the problem is more with LuaTeX than Gregorio per se.  The proposition is really a workaround to the weirdness of TeX.  It's pretty much not a good idea to have filenames with spaces in them when dealing with TeX.

**Comment by eschwab** [comment]
The implementation that I am working on does this (for auto or force compile only):

- Takes the filename given in `\gregorioscore`.
- Separates the path to the file and the root of the filename: `Chant/Hymns/Salve Regina.gabc` becomes `Chant/Hynms/` and `Salve Regina`
- Cleans up unwanted characters from the root of the filename: `Salve Regina` becomes `Salve-Regina`
- Adds the path back to the cleaned up name with the necessary extensions: `Chant/Hymns/Salve-Regina.{glog-gtex}`
- Then what gets put in the `gregorio` command is properly quoted for the shell.
- What goes to TeX is a clean "TeX friendly" filename.

The benefit of this is that the original filename is not changed on disk, so no surprises to the user. All the auto-generated files are "TeX friendly" and should still picked up by our garbage collection / old version cleanup.

**Comment by eroux** [comment]
sounds good to me

**Comment by eroux** [comment]
@eschwab any news on this?

**Comment by eschwab** [comment]
Yes, I have a fix ready. Just need to run the tests which I should have time to do tomorrow since the semester is finally over.

**Comment by eschwab** [comment]
For the changlog entry should this be filed under the Fixed or Added section?

**Comment by henryso** [comment]
I'd say fixed.  Most people would consider the old behavior a bug.

Henry

**Comment by rpspringuel** [comment]
What's the status here?  Can this go into 5.0?

**Comment by eschwab** [comment]
Fixed by #1344

**Comment by fiat96** [comment]
This issue is still ocurring.  I just updated to TeXLive 2024 just to be sure.

MWE:
```\documentclass{article}
\usepackage[autocompile]{gregoriotex}

\begin{document}
	\gabcsnippet{(c4) Test(c)}
\end{document}
```
When saved as "space.tex" the output is as expected:
![image](https://github.com/user-attachments/assets/2ad65377-7e2d-4b9d-89d6-b24630c4c58b)

When saved as "s p a c e.tex" the output log is: 
```This is LuaHBTeX, Version 1.18.0 (TeX Live 2024)  (format=lualatex 2024.11.19)  19 NOV 2024 11:44
 system commands enabled.
**"s p a c e.tex"
("./s p a c e.tex"
LaTeX2e <2024-11-01>
L3 programming layer <2024-11-02>
Lua module: luaotfload 2024-02-14 v3.28 Lua based OpenType font support
Lua module: lualibs 2023-07-13 v2.76 ConTeXt Lua standard libraries.
Lua module: lualibs-extended 2023-07-13 v2.76 ConTeXt Lua libraries -- extended 
collection.
luaotfload | conf : Root cache directory is "C:/texlive/2024/texmf-var/luatex-ca
che/generic/names".
luaotfload | init : Loading fontloader "fontloader-2023-12-28.lua" from kpse-res
olved path "c:/texlive/2024/texmf-dist/tex/luatex/luaotfload/fontloader-2023-12-
28.lua".
Lua-only attribute luaotfload@noligature = 1
luaotfload | init : Context OpenType loader version 3.134
Inserting `luaotfload.node_processor' in `pre_linebreak_filter'.
Inserting `luaotfload.node_processor' in `hpack_filter'.
Inserting `luaotfload.glyph_stream' in `glyph_stream_provider'.
Inserting `luaotfload.define_font' in `define_font'.
Lua-only attribute luaotfload_color_attribute = 2
luaotfload | conf : Root cache directory is "C:/texlive/2024/texmf-var/luatex-ca
che/generic/names".
Inserting `luaotfload.harf.strip_prefix' in `find_opentype_file'.
Inserting `luaotfload.harf.strip_prefix' in `find_truetype_file'.
Removing  `luaotfload.glyph_stream' from `glyph_stream_provider'.
Inserting `luaotfload.harf.glyphstream' in `glyph_stream_provider'.
Inserting `luaotfload.harf.finalize_vlist' in `post_linebreak_filter'.
Inserting `luaotfload.harf.finalize_hlist' in `hpack_filter'.
Inserting `luaotfload.cleanup_files' in `wrapup_run'.
Inserting `luaotfload.harf.finalize_unicode' in `finish_pdffile'.
Inserting `luaotfload.glyphinfo' in `glyph_info'.
Lua-only attribute luaotfload.letterspace_done = 3
Inserting `luaotfload.aux.set_sscale_dimens' in `luaotfload.patch_font'.
Inserting `luaotfload.aux.set_font_index' in `luaotfload.patch_font'.
Inserting `luaotfload.aux.patch_cambria_domh' in `luaotfload.patch_font'.
Inserting `luaotfload.aux.fixup_fontdata' in `luaotfload.patch_font_unsafe'.
Inserting `luaotfload.aux.set_capheight' in `luaotfload.patch_font'.
Inserting `luaotfload.aux.set_xheight' in `luaotfload.patch_font'.
Inserting `luaotfload.rewrite_fontname' in `luaotfload.patch_font'.
Inserting `tracingstacklevels' in `input_level_string'. (c:/texlive/2024/texmf-
dist/tex/latex/base/article.cls
Document Class: article 2024/06/29 v1.4n Standard LaTeX document class
(c:/texlive/2024/texmf-dist/tex/latex/base/size10.clo
File: size10.clo 2024/06/29 v1.4n Standard LaTeX file (size option)
luaotfload | db : Font names database loaded from C:/texlive/2024/texmf-var/luat
ex-cache/generic/names/luaotfload-names.luc.gz)
\c@part=\count194
\c@section=\count195
\c@subsection=\count196
\c@subsubsection=\count197
\c@paragraph=\count198
\c@subparagraph=\count199
\c@figure=\count266
\c@table=\count267
\abovecaptionskip=\skip49
\belowcaptionskip=\skip50
\bibindent=\dimen140
)
(c:/texlive/2024/texmf-dist/tex/lualatex/gregoriotex/gregoriotex.sty
Package: gregoriotex 2021/03/13 v6.0.0 GregorioTeX system.

(c:/texlive/2024/texmf-dist/tex/generic/iftex/iftex.sty
Package: iftex 2022/02/03 v1.0f TeX engine tests
)
(c:/texlive/2024/texmf-dist/tex/latex/xcolor/xcolor.sty
Package: xcolor 2024/09/29 v3.02 LaTeX color extensions (UK)

(c:/texlive/2024/texmf-dist/tex/latex/graphics-cfg/color.cfg
File: color.cfg 2016/01/02 v1.6 sample color configuration
)
Package xcolor Info: Driver file: luatex.def on input line 274.

(c:/texlive/2024/texmf-dist/tex/latex/graphics-def/luatex.def
File: luatex.def 2024/04/13 v1.2e Graphics/color driver for luatex
)
(c:/texlive/2024/texmf-dist/tex/latex/graphics/mathcolor.ltx)
Package xcolor Info: Model `cmy' substituted by `cmy0' on input line 1349.
Package xcolor Info: Model `hsb' substituted by `rgb' on input line 1353.
Package xcolor Info: Model `RGB' extended on input line 1365.
Package xcolor Info: Model `HTML' substituted by `rgb' on input line 1367.
Package xcolor Info: Model `Hsb' substituted by `hsb' on input line 1368.
Package xcolor Info: Model `tHsb' substituted by `hsb' on input line 1369.
Package xcolor Info: Model `HSB' substituted by `hsb' on input line 1370.
Package xcolor Info: Model `Gray' substituted by `gray' on input line 1371.
Package xcolor Info: Model `wave' substituted by `hsb' on input line 1372.
)
(c:/texlive/2024/texmf-dist/tex/latex/luacolor/luacolor.sty
Package: luacolor 2023-08-18 v1.18 Color support via LuaTeX's attributes (HO)
Inserting `luacolor.process' in `pre_shipout_filter'.
\LuaCol@Attribute=\attribute4
)
(c:/texlive/2024/texmf-dist/tex/latex/kvoptions/kvoptions.sty
Package: kvoptions 2022-06-15 v3.15 Key value format for package options (HO)

(c:/texlive/2024/texmf-dist/tex/latex/graphics/keyval.sty
Package: keyval 2022/05/29 v1.15 key=value parser (DPC)
\KV@toks@=\toks17
)
(c:/texlive/2024/texmf-dist/tex/generic/ltxcmds/ltxcmds.sty
Package: ltxcmds 2023-12-04 v1.26 LaTeX kernel commands for general use (HO)
)
(c:/texlive/2024/texmf-dist/tex/latex/kvsetkeys/kvsetkeys.sty
Package: kvsetkeys 2022-10-05 v1.19 Key value parser (HO)
))
(c:/texlive/2024/texmf-dist/tex/latex/graphics/graphicx.sty
Package: graphicx 2021/09/16 v1.2d Enhanced LaTeX Graphics (DPC,SPQR)

(c:/texlive/2024/texmf-dist/tex/latex/graphics/graphics.sty
Package: graphics 2024/08/06 v1.4g Standard LaTeX Graphics (DPC,SPQR)

(c:/texlive/2024/texmf-dist/tex/latex/graphics/trig.sty
Package: trig 2023/12/02 v1.11 sin cos tan (DPC)
)
(c:/texlive/2024/texmf-dist/tex/latex/graphics-cfg/graphics.cfg
File: graphics.cfg 2016/06/04 v1.11 sample graphics configuration
)
Package graphics Info: Driver file: luatex.def on input line 106.
)
\Gin@req@height=\dimen141
\Gin@req@width=\dimen142
)
(c:/texlive/2024/texmf-dist/tex/luatex/luatexbase/luatexbase.sty
Package: luatexbase 2015/10/04 v1.3 luatexbase interface to LuaTeX 

(c:/texlive/2024/texmf-dist/tex/luatex/ctablestack/ctablestack.sty
Package: ctablestack 2015/10/01 v1.0 Catcode table stable support
\@catcodetablestackcnt=\count268
)
\CatcodeTableOther=\catcodetable14
\CatcodeTableExpl=\catcodetable15
)
(c:/texlive/2024/texmf-dist/tex/luatex/luamplib/luamplib.sty
Package: luamplib 2024/11/12 v2.35.0 mplib package for LuaTeX
Lua module: luamplib 2024/11/12 v2.35.0 Lua package to typeset Metapost with Lua
TeX's MPLib.
\luamplibcctabexplat=\catcodetable16
\mplibtmptoks=\toks18
\mplibscratchbox=\box52
)
(c:/texlive/2024/texmf-dist/tex/generic/xstring/xstring.sty
(c:/texlive/2024/texmf-dist/tex/generic/xstring/xstring.tex
\xs_counta=\count269
\xs_countb=\count270
)
Package: xstring 2023/08/22 v1.86 String manipulations (CT)
)
(c:/texlive/2024/texmf-dist/tex/luatex/gregoriotex/gregoriotex-main.tex
(c:/texlive/2024/texmf-dist/tex/luatex/gregoriotex/gregoriotex-common.tex)
\gre@attr@dash=\attribute5
\gre@attr@center=\attribute6
\GreScoreId=\attribute7
\gre@attr@glyph@id=\attribute8
\gre@attr@glyph@top=\attribute9
\gre@attr@glyph@bottom=\attribute10
\gre@attr@syllable@id=\attribute11
\gre@atletter=\catcodetable17
Lua module: gregoriotex 2021/03/13 v6.0.0 GregorioTeX module.
Custom whatsit marker = 1
Module gregoriotex Info: marker whatsit id is 1 on input line 121

("s p a c e".gaux)
Inserting `gregoriotex.write_greaux' in `finish_pdffile'.
\gre@gaux=\write3
\gre@read@temp=\read2
\gre@factor=\count271

(c:/texlive/2024/texmf-dist/tex/luatex/gregoriotex/gregoriotex-spaces.tex
\gre@saved@prescore@hyphenpenalty=\count272
\gre@saved@prescore@exhyphenpenalty=\count273
\gre@saved@prescore@exhyphenchar=\count274
\gre@saved@prescore@doublehyphendemerits=\count275
\gre@saved@prescore@finalhyphendemerits=\count276
\gre@saved@prescore@brokenpenalty=\count277
\gre@saved@prescore@looseness=\count278
\gre@saved@prescore@tolerance=\count279
\gre@saved@prescore@pretolerance=\count280
\gre@saved@prescore@emergencystretch=\skip51
\gre@saved@prescore@widowpenalty=\count281
\gre@saved@prescore@clubpenalty=\count282
\gre@saved@prescore@parskip=\skip52
\gre@saved@prescore@lineskip=\skip53
\gre@saved@prescore@baselineskip=\skip54
\gre@saved@prescore@lineskiplimit=\skip55
\gre@dimen@textlower=\dimen143
\gre@dimen@stafflinewidth=\dimen144
\gre@dimen@linewidth=\dimen145
\gre@dimen@stafflineheight=\dimen146
\gre@dimen@interstafflinespace=\dimen147
\gre@dimen@stafflinediff=\dimen148
\gre@dimen@constantglyphraise=\dimen149
\gre@dimen@staffheight=\dimen150
\gre@skip@syllablefinalskip=\skip56
\gre@skip@minTextDistance=\skip57
\gre@skip@minNotesDistance=\skip58
\gre@dimen@curTextDistance=\dimen151
\gre@dimen@curNotesDistance=\dimen152
\gre@skip@minShiftText=\skip59
\gre@skip@minShiftNotes=\skip60
\gre@dimen@bolshift=\dimen153
\gre@dimen@bolextra=\dimen154
\gre@dimen@clefwidth@current=\dimen155
\gre@dimen@clefwidth@largest=\dimen156
\gre@dimen@clefwidth@bol=\dimen157
\gre@dimen@eolshift=\dimen158
\gre@dimen@glyphraisevalue=\dimen159
\gre@dimen@additionalbottomspace=\dimen160
\gre@dimen@additionaltopspace=\dimen161
\gre@dimen@additionaltopspacealt=\dimen162
\gre@dimen@additionaltopspacenabc=\dimen163
\gre@space@count@additionaltopspacethreshold=\count283
\gre@space@count@additionaltopspacealtthreshold=\count284
\gre@space@count@additionaltopspacenabcthreshold=\count285
\gre@space@count@noteadditionalspacelinestextthreshold=\count286
\gre@saved@prediscretionary@dimen@additionalbottomspace=\dimen164
\gre@saved@prediscretionary@dimen@additionaltopspace=\dimen165
\gre@saved@prediscretionary@dimen@additionaltopspacealt=\dimen166
\gre@saved@prediscretionary@dimen@additionaltopspacenabc=\dimen167
\gre@saved@prediscretionary@dimen@currenttranslationheight=\dimen168
\gre@saved@prediscretionary@dimen@textlower=\dimen169
\gre@saved@prediscretionary@dimen@currentabovelinestextheight=\dimen170
\gre@saved@prediscretionary@dimen@constantglyphraise=\dimen171
\gre@dimen@textaligncenter=\dimen172
\gre@dimen@enddifference=\dimen173
\gre@dimen@previousenddifference=\dimen174
\gre@dimen@currenttranslationheight=\dimen175
\gre@skip@nextbegindifference=\skip61
\gre@dimen@annotationtrueraise=\dimen176
\gre@dimen@commentarytrueraise=\dimen177
\gre@skip@bar@requirement=\skip62
\gre@skip@bar@allocation=\skip63
\gre@dimen@bar@shift=\dimen178
\gre@skip@text@requirement=\skip64
\gre@skip@text@allocation=\skip65
\gre@dimen@text@shift=\dimen179
\gre@dimen@adjustedpreviousenddifference=\dimen180
\gre@skip@adjustednextbegindifference=\dimen181
\gre@skip@punctummorashift=\skip66
\gre@skip@alterationshift=\skip67
\gre@dimen@begindifference=\dimen182
\gre@dimen@lastglyphwidth=\dimen183
\gre@dimen@notesaligncenter=\dimen184
\gre@dimen@additionalleftspace=\dimen185
\gre@dimen@initialwidth=\dimen186
\gre@dimen@currentabovelinestextheight=\dimen187
\gre@dimen@temp@one=\dimen188
\gre@dimen@temp@two=\dimen189
\gre@dimen@temp@three=\dimen190
\gre@dimen@temp@four=\dimen191
\gre@dimen@temp@five=\dimen192
\gre@skip@temp@one=\skip68
\gre@skip@temp@two=\skip69
\gre@skip@temp@three=\skip70
\gre@skip@temp@four=\skip71
\gre@count@temp@one=\count287
\gre@count@temp@two=\count288
\gre@count@temp@three=\count289
\gre@space@count@newlinepenalty=\count290
\gre@space@count@nobreakpenalty=\count291
\gre@space@count@endofwordpenalty=\count292
\gre@space@count@endofsyllablepenalty=\count293
\gre@space@count@endafterbarpenalty=\count294
\gre@space@count@endafterbaraltpenalty=\count295
\gre@space@count@finalpenalty=\count296
\gre@space@count@endofelementpenalty=\count297
\gre@space@count@hyphenpenalty=\count298
\gre@space@count@brokenpenalty=\count299
\gre@space@count@looseness=\count300
\gre@space@count@tolerance=\count301
\gre@space@count@pretolerance=\count302
\gre@space@count@widowpenalty=\count303
\gre@space@count@clubpenalty=\count304
\greconffactor=\count305
)
\gre@box@temp@width=\box53
\gre@box@initial=\box54
\gre@biginitial=\count306
\gre@knownline=\count307
\gre@box@annotation=\box55
\gre@box@add=\box56
\gre@box@old=\box57
\gre@count@annotationvalign=\count308
\gre@box@commentary=\box58
\gre@box@lines=\box59
Module gregoriotex Info: Registering variant font greciliae as gre@font@variant@
A. on input line 987
Module gregoriotex Info: Registering variant font greciliae-hollow as gre@font@v
ariant@B. on input line 987
Module gregoriotex Info: Registering variant font greciliae-hole as gre@font@var
iant@C. on input line 987
luaotfload | cache : Lookup cache loaded from C:/texlive/2024/texmf-var/luatex-c
ache/generic/names/luaotfload-lookup-cache.luc.
Module gregoriotex Info: Mapping font greciliae on input line 992
Module gregoriotex Info: Mapping font greciliae-hollow on input line 992
Module gregoriotex Info: Mapping font greciliae-hole on input line 992

(c:/texlive/2024/texmf-dist/tex/luatex/gregoriotex/gregoriotex-chars.tex
\gre@box@hep=\box60
)
(c:/texlive/2024/texmf-dist/tex/luatex/gregoriotex/gregoriotex-signs.tex
\gre@box@temp@clef=\box61
\gre@box@temp@cleftwo=\box62
\greslurheight=\dimen193
\gre@box@temp@sign=\box63
\gre@count@shiftaftermora=\count309
\gre@dimen@morawidth=\dimen194
\gre@skip@bar@lastskip=\skip72
\gre@count@lastglyphiscavum=\count310
)
(c:/texlive/2024/texmf-dist/tex/luatex/gregoriotex/gregoriotex-syllable.tex
\gre@generate@pointandclick=\count311
\gre@box@syllablenotes=\box64
\gre@box@syllabletext=\box65
\gre@clivisalignment=\count312
\gre@count@unbreakabletotalnotes=\count313
\gre@count@unbreakableinitialnotes=\count314
\gre@count@unbreakablefinalnotes=\count315
\gre@count@syllablenotes=\count316
)
\gre@variableheightexpansion=\count317
\gre@lastoflinecount=\count318
\gre@saved@prenlba@nobreakpenalty=\count319
\gre@saved@prenlba@endofwordpenalty=\count320
\gre@saved@prenlba@endofsyllablepenalty=\count321
\gre@saved@prenlba@endafterbarpenalty=\count322
\gre@saved@prenlba@endafterbaraltpenalty=\count323
\gre@saved@prenlba@endofelementpenalty=\count324
\gre@saved@prenlba@hyphenpenalty=\count325
\gre@lasteuouaeindex=\count326

(c:/texlive/2024/texmf-dist/tex/luatex/gregoriotex/gregoriotex-symbols.tex
Module gregoriotex Info: Registering variant font greextra as gre@font@variant@D
. on input line 53
)
\gre@dimen@stafflinethicknessbase=\dimen195
\gre@dimen@glyphraisebase=\dimen196
\gre@dimen@interstafflinedistancebase=\dimen197
\gre@dimen@inclinatumonlinemoravshiftbase=\dimen198
\gre@dimen@inclinatumonlinemorahshiftbase=\dimen199
\gre@dimen@inclinatumofflinemorahshiftbase=\dimen256

(c:/texlive/2024/texmf-dist/tex/luatex/gregoriotex/gregoriotex-gsp-default.tex) (c:/texlive/2024/texmf-dist/tex/luatex/gregoriotex/gregoriotex-nabc.tex)))
(c:/texlive/2024/texmf-dist/tex/latex/l3backend/l3backend-luatex.def
File: l3backend-luatex.def 2024-05-08 L3 backend support: PDF output (LuaTeX)
\l__color_backend_stack_int=\count327
Inserting `l3color' in `luaotfload.parse_color'.
\l__pdf_internal_box=\box66
)
("./s p a c e.aux")
\openout1 = s p a c e.aux

LaTeX Font Info:    Checking defaults for OML/cmm/m/it on input line 4.
LaTeX Font Info:    ... okay on input line 4.
LaTeX Font Info:    Checking defaults for OMS/cmsy/m/n on input line 4.
LaTeX Font Info:    ... okay on input line 4.
LaTeX Font Info:    Checking defaults for OT1/cmr/m/n on input line 4.
LaTeX Font Info:    ... okay on input line 4.
LaTeX Font Info:    Checking defaults for T1/cmr/m/n on input line 4.
LaTeX Font Info:    ... okay on input line 4.
LaTeX Font Info:    Checking defaults for TS1/cmr/m/n on input line 4.
LaTeX Font Info:    ... okay on input line 4.
LaTeX Font Info:    Checking defaults for TU/lmr/m/n on input line 4.
LaTeX Font Info:    ... okay on input line 4.
LaTeX Font Info:    Checking defaults for OMX/cmex/m/n on input line 4.
LaTeX Font Info:    ... okay on input line 4.
LaTeX Font Info:    Checking defaults for U/cmr/m/n on input line 4.
LaTeX Font Info:    ... okay on input line 4.

(c:/texlive/2024/texmf-dist/tex/context/base/mkii/supp-pdf.mkii
[Loading MPS to PDF converter (version 2006.09.02).]
\scratchcounter=\count328
\scratchdimen=\dimen257
\scratchbox=\box67
\nofMPsegments=\count329
\nofMParguments=\count330
\everyMPshowfont=\toks19
\MPscratchCnt=\count331
\MPscratchDim=\dimen258
\MPnumerator=\count332
\makeMPintoPDFobject=\count333
\everyMPtoPDFconversion=\toks20
) (c:/texlive/2024/texmf-dist/tex/latex/epstopdf-pkg/epstopdf-base.sty
Package: epstopdf-base 2020-01-24 v2.11 Base part for package epstopdf
Package epstopdf-base Info: Redefining graphics rule for `.eps' on input line 4
85.

(c:/texlive/2024/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg
File: epstopdf-sys.cfg 2010/07/13 v1.3 Configuration of (r)epstopdf for TeX Liv
e
))
Module gregoriotex Info: Processing gabc snippet... on input line 5
...e/2024/texmf-dist/tex/luatex/gregoriotex/gregoriotex.lua:969: attempt to inde
x a nil value (local 'f')
stack traceback:
	...e/2024/texmf-dist/tex/luatex/gregoriotex/gregoriotex.lua:969: in field 'dire
ct_gabc'
	[\directlua]:1: in main chunk.
\gabcsnippet ... \gre@allowdeprecated@asboolean )}
                                                  
l.5 	\gabcsnippet{(c4) Test(c)}
                             
The lua interpreter ran into a problem, so the
remainder of this lua chunk will be ignored.

("./s p a c e.aux")
 ***********
LaTeX2e <2024-11-01>
L3 programming layer <2024-11-02>
 ***********
)

Here is how much of LuaTeX's memory you used:
 20254 strings out of 475664
 100000,794899 words of node,token memory allocated
 449 words of node memory still in use:
   3 hlist, 1 vlist, 1 rule, 2 glue, 3 kern, 2 glyph, 11 attribute, 49 glue_spec
, 7 attribute_list, 2 write, 1 user_defined, 1 pdf_colorstack nodes
   avail lists: 2:8,3:1,4:1,5:4,7:1,9:1
 43046 multiletter control sequences out of 65536+600000
 19 fonts using 3440103 bytes
 72i,1n,75p,593b,55s stack positions out of 10000i,1000n,20000p,200000b,200000s

warning  (pdf backend): no pages of output.

PDF statistics: 0 PDF objects out of 1000 (max. 8388607)
 0 named destinations out of 1000 (max. 131072)
 1 words of extra memory for PDF output out of 10000 (max. 100000000)

```

**Comment by fiat96** [comment]
@rpspringuel Bumping this issue, request re-opening. 

The fix applied works for spaces in .gabc files, but the issue persists if there is a space in the .tex file.

**Comment by rpspringuel** [comment]
That's not something we can fix.  LuaLaTeX does not allow spaces in tex filenames.  So far as I know, no flavor of TeX does.
