### ISSUE TITLE
vertical and horizontal episem crossing

### ISSUE THREAD

**Issue by jperon** [gregorio-project/gregorio#395]
This figure is quite frequent : 

    Test.(ghg'_)

Here is the output we get : the vertical episem should be placed lower to avoid "collision".

![mwe](https://cloud.githubusercontent.com/assets/4775231/7550892/ec920756-f673-11e4-8ff0-a2da4a13fb64.png)

**Comment by eroux** [comment]
In the original file, are the two episemus at the bottom or is one at the top?

**Comment by jperon** [comment]
You're right, my mistake : the horizontal episem should be above.
Here is an even more interresting case : it should be possible to have an episem over the note, bridged with the following one ; it's not possible, neither with `ghf'_/g_f'fe.` (that gives the result below), nor with `ghf'/g__f'fe.` (that gives an episem only on the note after the neumatic cut).

![mwe](https://cloud.githubusercontent.com/assets/4775231/7561344/913da00a-f7cb-11e4-85db-54cc6e77879a.png)

**Comment by jperon** [comment]
N.B : in all such cases, the horizontal episem is quite high, as if it where above the higher note of the torculus.

**Comment by eroux** [comment]
So I believe it's a combination of #389 + #40 (not the original issue, but what it turned out to be in the comments). @henryso if you agree, you can mark as duplicate. @jperon it should be fixed in 4.0

**Comment by jperon** [comment]
Should it be fixed in `develop` or in future 4.0 ? I'm testing on develop now.

**Comment by jakubjelinek** [comment]
Sounds like https://gna.org/bugs/?22639

**Comment by eroux** [comment]
It's not fixed yet, but the fix is planned for 4.0. @jakubjelinek yes, this is a variant of the bug

**Comment by eroux** [comment]
Thinking back about it, I think it might be useful to have both below (it's certainly a bit more readable in some cases), and Gregorio should handle that too... So keeping this open. But it can be for a release after 4.0, no emergency.
